"""Extra AI tools imported from the AI_Tools_Database.xlsx.
Concise entries (start_here_workflow / make_money / irl are minimal — admin can enrich)."""

def _slug(name: str) -> str:
    import re
    s = name.lower()
    s = re.sub(r'[^a-z0-9]+', '-', s)
    return s.strip('-')


# Category slug mapping from Excel primary → our taxonomy
CAT_MAP = {
    "AI Chatbots": "chat",
    "AI Search Engines": "research",
    "AI Copywriting": "writing",
    "AI Writing": "writing",
    "AI Email Assistants": "productivity",
    "AI Presentation Makers": "design",
    "AI Resume Builders": "hr",
    "AI Interview Preparation": "hr",
    "AI Coding Assistants": "code",
    "AI IDEs": "code",
    "AI Code Review": "code",
    "AI Cybersecurity": "security",
    "AI Data Analysis": "data",
    "AI SQL Tools": "data",
    "AI PDF Chat": "productivity",
    "AI Academic Tools": "research",
    "AI Citation Tools": "research",
    "AI Note Taking": "productivity",
    "AI Knowledge Management": "productivity",
    "AI Meeting Assistants": "productivity",
    "AI Image Generation": "image",
    "AI Video Generation": "video",
    "AI Voice Cloning": "audio",
    "AI Music Generation": "audio",
    "AI Text-to-Speech": "audio",
    "AI Speech-to-Text": "audio",
    "AI Design Tools": "design",
    "AI Marketing": "marketing",
    "AI SEO Tools": "marketing",
    "AI Social Media": "marketing",
    "AI Sales Tools": "sales-crm",
    "AI CRM": "sales-crm",
    "AI Customer Support": "support",
    "AI Automation": "workflow-builders",
    "AI Agents": "ai-agents",
    "AI Prompt Engineering": "productivity",
    "AI Translation": "productivity",
    "AI OCR": "doc-automation",
    "AI Gaming": "image",
    "AI 3D Generation": "image",
    "AI Biology": "research",
    "AI Document Processing": "doc-automation",
}

# Pricing normalization
def _price(free_plan, model):
    fp = (free_plan or "").strip().lower()
    m = (model or "").strip().lower()
    if "free" in m and "freemium" not in m and "subscription" not in m and fp == "yes":
        return "free"
    if fp == "yes":
        return "freemium"
    return "paid"


# Raw tool rows (from AI_Tools_Database.xlsx). Deduped against seed_data.TOOLS by slug at import.
RAW = [
    ("Gemini", "Google", "https://gemini.google.com", "AI Chatbots", "Google's multimodal assistant integrated with Workspace and Search", "Google ecosystem users, multimodal tasks", "Yes", "Freemium ($19.99/mo Advanced)"),
    ("Microsoft Copilot", "Microsoft", "https://copilot.microsoft.com", "AI Chatbots", "AI assistant embedded across Windows, Edge, and Microsoft 365", "Microsoft 365 users, enterprise productivity", "Yes", "Freemium"),
    ("Grok", "xAI", "https://grok.com", "AI Chatbots", "Conversational AI integrated with X (Twitter) with real-time data access", "Real-time trends, X-native queries, casual tone", "Yes", "Freemium"),
    ("Pi", "Inflection AI", "https://pi.ai", "AI Chatbots", "Emotionally supportive personal AI companion chatbot", "Casual conversation, emotional support", "Yes", "Free"),
    ("Character.AI", "Character.AI", "https://character.ai", "AI Chatbots", "Platform for creating and chatting with custom AI personas", "Roleplay, entertainment, fan characters", "Yes", "Freemium"),
    ("Copy.ai", "Copy.ai", "https://www.copy.ai", "AI Copywriting", "AI workflow platform for marketing and sales copy generation", "Sales outreach, ad copy, GTM workflows", "Yes", "Freemium"),
    ("Writesonic", "Writesonic", "https://writesonic.com", "AI Copywriting", "AI writer for SEO articles, ads, and marketing copy", "SEO content production, ad copy", "Yes", "Freemium"),
    ("Grammarly", "Grammarly", "https://www.grammarly.com", "AI Writing", "AI writing assistant for grammar, tone, and clarity across apps", "Everyday writing correction and tone adjustment", "Yes", "Freemium"),
    ("QuillBot", "QuillBot", "https://quillbot.com", "AI Writing", "AI paraphrasing, grammar, and summarization tool", "Academic writing, paraphrasing", "Yes", "Freemium"),
    ("Sudowrite", "Sudowrite", "https://www.sudowrite.com", "AI Writing", "AI writing partner built specifically for novelists and fiction writers", "Long-form fiction and creative writing", "No", "Subscription"),
    ("Rytr", "Rytr", "https://rytr.me", "AI Copywriting", "Budget-friendly AI writing assistant for short-form content", "Solopreneurs and small businesses", "Yes", "Freemium"),
    ("Superhuman", "Superhuman", "https://superhuman.com", "AI Email Assistants", "Premium email client with AI triage and writing assistance", "Power users managing high email volume", "No", "Subscription"),
    ("Shortwave", "Shortwave", "https://www.shortwave.com", "AI Email Assistants", "Gmail client with AI search, summarization, and auto-labeling", "Gmail power users wanting AI search/summaries", "Yes", "Freemium"),
    ("Beautiful.ai", "Beautiful.ai", "https://www.beautiful.ai", "AI Presentation Makers", "AI-assisted slide design tool with smart templates", "Business presentations needing consistent design", "No", "Subscription"),
    ("Tome", "Tome", "https://tome.app", "AI Presentation Makers", "AI storytelling and narrative deck generator", "Sales narratives and pitch decks", "Yes", "Freemium"),
    ("Decktopus", "Decktopus", "https://www.decktopus.com", "AI Presentation Makers", "AI presentation generator with built-in analytics", "Marketers needing quick, trackable decks", "Yes", "Freemium"),
    ("Teal", "Teal", "https://www.tealhq.com", "AI Resume Builders", "AI-powered resume builder and job application tracker", "Job seekers managing multiple applications", "Yes", "Freemium"),
    ("Kickresume", "Kickresume", "https://www.kickresume.com", "AI Resume Builders", "AI resume and cover letter builder with recruiter-vetted templates", "Job seekers wanting polished templates fast", "Yes", "Freemium"),
    ("Final Round AI", "Final Round AI", "https://www.finalroundai.com", "AI Interview Preparation", "Real-time AI interview copilot and mock interview practice", "Technical and behavioral interview prep", "No", "Subscription"),
    ("Interview Warmup", "Google", "https://grow.google/certificates/interview-warmup", "AI Interview Preparation", "Free Google tool for practicing interview answers with AI feedback", "Free, casual interview practice", "Yes", "Free"),
    ("Claude Code", "Anthropic", "https://www.anthropic.com/claude-code", "AI Coding Assistants", "Agentic command-line and IDE tool for delegating coding tasks to Claude", "Multi-step coding tasks, refactors, agentic workflows", "Yes", "Usage-based"),
    ("Windsurf", "Windsurf (Codeium)", "https://windsurf.com", "AI IDEs", "AI-native IDE with agentic Cascade flows for multi-step coding", "Agentic multi-file coding workflows", "Yes", "Freemium"),
    ("Replit", "Replit", "https://replit.com", "AI IDEs", "Cloud-based IDE with built-in AI agent for building and deploying apps", "Beginners and rapid prototyping/deployment", "Yes", "Freemium"),
    ("Tabnine", "Tabnine", "https://www.tabnine.com", "AI Coding Assistants", "Enterprise privacy-focused AI code completion with on-prem deployment options", "Enterprises with strict code-privacy requirements", "Yes", "Freemium"),
    ("Codeium", "Codeium", "https://windsurf.com", "AI Coding Assistants", "Free AI code completion engine (now part of Windsurf)", "Free in-editor autocomplete", "Yes", "Freemium"),
    ("Sourcegraph Cody", "Sourcegraph", "https://sourcegraph.com/cody", "AI Code Review", "AI coding assistant with deep codebase-wide context search", "Large codebase navigation and review", "Yes", "Freemium"),
    ("CodeRabbit", "CodeRabbit", "https://www.coderabbit.ai", "AI Code Review", "AI tool that automatically reviews pull requests with inline comments", "Automated PR review in CI pipelines", "Yes", "Freemium"),
    ("Snyk", "Snyk", "https://snyk.io", "AI Cybersecurity", "AI-assisted security scanning for code, dependencies, and containers", "Finding/fixing vulnerabilities in code", "Yes", "Freemium"),
    ("Julius AI", "Julius AI", "https://julius.ai", "AI Data Analysis", "AI data analyst that writes and runs code on uploaded datasets", "Non-technical users analyzing spreadsheets/CSVs", "Yes", "Freemium"),
    ("Hex", "Hex Technologies", "https://hex.tech", "AI Data Analysis", "Collaborative notebook platform with AI-assisted analytics", "Data teams building collaborative analytics workflows", "Yes", "Freemium"),
    ("AI2SQL", "AI2sql", "https://www.ai2sql.io", "AI SQL Tools", "Converts natural language into SQL queries", "Non-SQL users querying databases", "Yes", "Freemium"),
    ("Seek AI", "Seek AI", "https://www.seek.ai", "AI Data Analysis", "Enterprise natural-language data querying and analytics platform", "Enterprise self-serve analytics", "No", "Enterprise"),
    ("NotebookLM", "Google", "https://notebooklm.google", "AI PDF Chat", "AI research assistant grounded only in user-uploaded sources", "Studying and synthesizing personal source documents", "Yes", "Free"),
    ("ChatPDF", "ChatPDF", "https://www.chatpdf.com", "AI PDF Chat", "Simple tool to chat with the contents of any PDF", "Quick Q&A over a single PDF", "Yes", "Freemium"),
    ("Elicit", "Elicit", "https://elicit.com", "AI Academic Tools", "AI research assistant for finding and synthesizing academic papers", "Literature reviews and systematic reviews", "Yes", "Freemium"),
    ("Consensus", "Consensus", "https://consensus.app", "AI Academic Tools", "AI search engine that extracts findings directly from research papers", "Quick evidence-based answers from scientific literature", "Yes", "Freemium"),
    ("Scite", "Scite.ai", "https://scite.ai", "AI Citation Tools", "Shows how a paper has been cited (supporting/contrasting) elsewhere", "Checking citation context and paper credibility", "Yes", "Freemium"),
    ("Semantic Scholar", "Allen Institute for AI", "https://www.semanticscholar.org", "AI Academic Tools", "Free AI-powered academic search engine and paper recommender", "Free academic literature discovery", "Yes", "Free"),
    ("Mem", "Mem Labs", "https://mem.ai", "AI Knowledge Management", "AI-native note-taking app that auto-organizes notes", "Self-organizing personal knowledge base", "No", "Subscription"),
    ("Fathom", "Fathom AI", "https://fathom.video", "AI Meeting Assistants", "Free AI meeting notetaker with CRM sync and follow-up emails", "Sales calls, customer interviews", "Yes", "Free"),
    ("Granola", "Granola", "https://www.granola.ai", "AI Meeting Assistants", "AI notepad that upgrades your notes with meeting transcripts", "Note-takers who prefer their own notes + AI cleanup", "Yes", "Freemium"),
    ("Fireflies.ai", "Fireflies.ai", "https://fireflies.ai", "AI Meeting Assistants", "Meeting recorder that transcribes, summarizes, and analyzes team calls", "Sales teams tracking calls at scale", "Yes", "Freemium"),
    ("DALL·E 3", "OpenAI", "https://openai.com/dall-e-3", "AI Image Generation", "OpenAI's flagship text-to-image model integrated with ChatGPT", "General-purpose creative image generation", "Yes", "Freemium"),
    ("Stable Diffusion", "Stability AI", "https://stability.ai", "AI Image Generation", "Open-source text-to-image model with a huge community and fine-tunes", "Custom models, fine-tuning, self-hosted image gen", "Yes", "Free"),
    ("Leonardo.ai", "Leonardo.ai", "https://leonardo.ai", "AI Image Generation", "Creative platform for AI images with fine-tuned models for game art & design", "Game art, concept art, ad creatives", "Yes", "Freemium"),
    ("Adobe Firefly", "Adobe", "https://firefly.adobe.com", "AI Image Generation", "Adobe's commercially-safe generative image models built into Creative Cloud", "Designers needing licensed generative AI", "Yes", "Freemium"),
    ("Recraft", "Recraft", "https://www.recraft.ai", "AI Image Generation", "AI design tool with vector-native output for brand-consistent graphics", "Designers, brand teams needing vector output", "Yes", "Freemium"),
    ("Kling", "Kuaishou", "https://kling.kuaishou.com", "AI Video Generation", "Text-to-video model producing longer, more coherent clips", "Cinematic short clips, storyboards", "Yes", "Freemium"),
    ("Pika", "Pika Labs", "https://pika.art", "AI Video Generation", "Fast, playful text/image-to-video tool loved by creators", "Fun social clips, animated ideas", "Yes", "Freemium"),
    ("Sora", "OpenAI", "https://openai.com/sora", "AI Video Generation", "OpenAI's text-to-video model for realistic short clips", "Cinematic storytelling, ad prototypes", "Yes", "Freemium"),
    ("Luma Dream Machine", "Luma AI", "https://lumalabs.ai/dream-machine", "AI Video Generation", "Realistic text/image-to-video model with strong motion", "Realistic short video clips", "Yes", "Freemium"),
    ("Veo", "Google DeepMind", "https://deepmind.google/technologies/veo", "AI Video Generation", "Google DeepMind's high-fidelity generative video model", "Cinematic 1080p AI video generation", "Yes", "Freemium"),
    ("CapCut", "ByteDance", "https://www.capcut.com", "AI Video Generation", "AI-powered video editor loved by TikTok/short-form creators", "Short-form video editing at scale", "Yes", "Freemium"),
    ("Play.ht", "Play.ht", "https://play.ht", "AI Text-to-Speech", "AI voice generation with 900+ voices across 140+ languages", "Podcasters, e-learning, IVR", "Yes", "Freemium"),
    ("Murf.ai", "Murf AI", "https://murf.ai", "AI Text-to-Speech", "Studio-quality AI voiceovers with multi-speaker dialogue", "Corporate videos, e-learning, audiobooks", "Yes", "Freemium"),
    ("Udio", "Udio", "https://www.udio.com", "AI Music Generation", "AI music generator competing with Suno for songs from prompts", "Songwriters, content creators", "Yes", "Freemium"),
    ("Whisper", "OpenAI", "https://openai.com/research/whisper", "AI Speech-to-Text", "Open-source multilingual speech recognition model", "Transcription in 90+ languages", "Yes", "Free"),
    ("AssemblyAI", "AssemblyAI", "https://www.assemblyai.com", "AI Speech-to-Text", "Speech-to-text API with topic detection, PII redaction and diarization", "Developers building voice apps", "Yes", "Freemium"),
    ("Figma AI", "Figma", "https://www.figma.com/ai", "AI Design Tools", "AI features across Figma design and FigJam whiteboards", "Designers speeding up mockups", "Yes", "Freemium"),
    ("Uizard", "Uizard", "https://uizard.io", "AI Design Tools", "Text-to-mockup AI design tool for wireframes and prototypes", "PMs and founders making quick UI mockups", "Yes", "Freemium"),
    ("Framer AI", "Framer", "https://www.framer.com/ai", "AI Design Tools", "AI website builder that generates production sites from prompts", "Landing pages and portfolio sites in minutes", "Yes", "Freemium"),
    ("Surfer SEO", "Surfer", "https://surferseo.com", "AI SEO Tools", "AI-powered SEO content editor with real-time optimization suggestions", "SEO content teams", "No", "Subscription"),
    ("Frase", "Frase.io", "https://www.frase.io", "AI SEO Tools", "AI content brief and article writer optimized for search intent", "SEO writers producing at scale", "No", "Subscription"),
    ("SEO.ai", "SEO.ai", "https://seo.ai", "AI SEO Tools", "AI SEO writing platform with keyword research + content generation", "Small SEO teams", "Yes", "Freemium"),
    ("Ahrefs AI", "Ahrefs", "https://ahrefs.com", "AI SEO Tools", "Ahrefs' AI features on top of its SEO/backlink dataset", "Serious SEOs & agencies", "Yes", "Subscription"),
    ("Buffer AI", "Buffer", "https://buffer.com", "AI Social Media", "Social media scheduling with an AI Assistant for content ideas + captions", "Solopreneurs managing multiple social accounts", "Yes", "Freemium"),
    ("Hootsuite OwlyWriter", "Hootsuite", "https://www.hootsuite.com/platform/owlywriter", "AI Social Media", "AI content generator baked into the Hootsuite social suite", "Social managers at agencies/brands", "Yes", "Subscription"),
    ("Ocoya", "Ocoya", "https://www.ocoya.com", "AI Social Media", "AI-powered social media content + scheduling with e-commerce integrations", "E-commerce social marketers", "Yes", "Freemium"),
    ("Apollo.io", "Apollo", "https://www.apollo.io", "AI Sales Tools", "AI sales engagement platform with 275M+ contact database", "SDRs and outbound teams", "Yes", "Freemium"),
    ("Salesloft", "Salesloft", "https://salesloft.com", "AI Sales Tools", "AI-driven sales cadence platform for revenue teams", "Sales orgs running structured cadences", "No", "Enterprise"),
    ("Gong", "Gong.io", "https://www.gong.io", "AI Sales Tools", "Revenue intelligence platform that records + analyzes sales calls with AI", "Enterprise sales teams", "No", "Enterprise"),
    ("Clay", "Clay", "https://www.clay.com", "AI Sales Tools", "AI-native prospecting platform to enrich, sequence, and personalize outbound", "Growth teams doing outbound at scale", "Yes", "Freemium"),
    ("HubSpot AI", "HubSpot", "https://www.hubspot.com", "AI CRM", "AI features baked into HubSpot's CRM, marketing and service hubs", "SMB CRM users wanting AI everywhere", "Yes", "Freemium"),
    ("Attio", "Attio", "https://attio.com", "AI CRM", "AI-native modern CRM built for teams that want customization", "Startups building bespoke CRM workflows", "Yes", "Freemium"),
    ("Sierra", "Sierra AI", "https://sierra.ai", "AI Customer Support", "Enterprise conversational AI agent platform for customer experience", "Enterprises deploying customer-facing agents", "No", "Enterprise"),
    ("Decagon", "Decagon AI", "https://decagon.ai", "AI Customer Support", "Enterprise customer support automation agent", "High-volume, high-complexity support automation", "No", "Enterprise"),
    ("Zapier", "Zapier", "https://zapier.com", "AI Automation", "Connect 6000+ apps with no-code triggers + AI-powered automations", "Marketers, ops, founders automating workflows", "Yes", "Freemium"),
    ("Make.com", "Make", "https://www.make.com", "AI Automation", "Visual automation with logic, branching, and AI modules", "Devs and marketers building complex scenarios", "Yes", "Freemium"),
    ("n8n", "n8n", "https://n8n.io", "AI Automation", "Open-source, self-hostable automation with a fair-code license", "Devs wanting self-hosted flows", "Yes", "Freemium"),
    ("OpenAI Operator", "OpenAI", "https://openai.com/index/introducing-operator", "AI Agents", "Autonomous browser-using agent for completing web tasks", "Automating multi-step browser tasks", "No", "Subscription"),
    ("AutoGPT", "Significant Gravitas", "https://autogpt.net", "AI Agents", "Open-source experimental autonomous agent framework", "Hobbyists prototyping autonomous loops", "Yes", "Free"),
    ("CrewAI", "CrewAI", "https://www.crewai.com", "AI Agents", "Open-source framework for role-based multi-agent collaboration", "Developers orchestrating teams of specialized agents", "Yes", "Free"),
    ("AutoGen", "Microsoft Research", "https://microsoft.github.io/autogen", "AI Agents", "Framework for building multi-agent conversational systems", "Prototyping multi-agent conversation patterns", "Yes", "Free"),
    ("Lindy", "Lindy AI", "https://www.lindy.ai", "AI Agents", "No-code AI agent builder for business/personal tasks", "Non-devs automating email, scheduling, and ops", "No", "Subscription"),
    ("Relevance AI", "Relevance AI", "https://relevanceai.com", "AI Agents", "No-code platform for building and orchestrating agent teams", "Building multi-agent teams without code", "Yes", "Freemium"),
    ("LangGraph", "LangChain Inc.", "https://langchain-ai.github.io/langgraph", "AI Agents", "Graph-based framework for building stateful, controllable agents", "Devs needing fine-grained agent state/flow", "Yes", "Free"),
    ("Harvey", "Harvey AI", "https://www.harvey.ai", "AI Agents", "Domain-specific AI agent for legal research and drafting", "Law firms automating research + drafting", "No", "Enterprise"),
    ("Hebbia", "Hebbia", "https://www.hebbia.com", "AI Agents", "AI agent platform for financial and professional research analysis", "Finance / PS teams analyzing large document sets", "No", "Enterprise"),
    ("PromptPerfect", "PromptPerfect", "https://promptperfect.jina.ai", "AI Prompt Engineering", "Tool that automatically optimizes prompts for better LLM outputs", "Prompt engineers", "Yes", "Freemium"),
    ("DeepL", "DeepL SE", "https://www.deepl.com", "AI Translation", "AI translation engine known for high translation accuracy and nuance", "Professional translation across 30+ languages", "Yes", "Freemium"),
    ("Adobe Acrobat AI Assistant", "Adobe", "https://www.adobe.com/acrobat/generative-ai-pdf.html", "AI OCR", "AI assistant embedded in Acrobat for summarizing and chatting with PDFs", "Pros dealing with PDFs daily", "No", "Subscription"),
    ("Meshy", "Meshy AI", "https://www.meshy.ai", "AI 3D Generation", "AI tool for generating 3D models and textures from text or images", "Game devs, 3D artists prototyping fast", "Yes", "Freemium"),
    ("Inworld AI", "Inworld AI", "https://inworld.ai", "AI Gaming", "Platform for building AI-driven NPCs and characters for games", "Game studios building interactive characters", "Yes", "Freemium"),
    ("Vimcal", "Vimcal AI", "https://www.vimcal.com", "AI Automation", "AI scheduling agent for coordinating meetings", "Pros automating meeting scheduling", "No", "Subscription"),
    ("11x", "11x.ai", "https://www.11x.ai", "AI Sales Tools", "Fully autonomous AI sales and recruiting agents (Alice/Jordan)", "Replacing/augmenting SDR and recruiter outbound", "No", "Enterprise"),
    ("Paradox Olivia", "Paradox", "https://www.paradox.ai", "AI CRM", "Conversational recruiting agent for screening and scheduling", "High-volume frontline hiring automation", "No", "Enterprise"),
    ("Perplexity Comet", "Perplexity AI", "https://www.perplexity.ai/comet", "AI Agents", "Browser-embedded agent that completes tasks across tabs", "Multi-tab autonomous research", "No", "Subscription"),
    ("Scale AI", "Scale AI", "https://scale.com", "AI Data Analysis", "Data labeling, RLHF, and evaluation infrastructure provider for AI labs", "AI labs training frontier models", "No", "Enterprise"),
    ("AlphaFold", "Google DeepMind", "https://alphafold.ebi.ac.uk", "AI Biology", "AI system that predicts 3D protein structures from amino acid sequences", "Biology researchers", "Yes", "Free"),
    ("IBM Watson Discovery", "IBM", "https://www.ibm.com/products/watson-discovery", "AI Document Processing", "Enterprise AI search and document analysis platform", "Enterprises with large document corpora", "No", "Enterprise"),
]


def build_extra_tools():
    out = []
    for row in RAW:
        name, company, url, cat, desc, best_for, free_plan, model = row
        slug = _slug(name)
        category = CAT_MAP.get(cat, "chat")
        out.append({
            "name": name,
            "slug": slug,
            "tagline": desc[:120],
            "description": f"{desc} By {company}.",
            "category": category,
            "category_slugs": [category],
            "pricing": _price(free_plan, model),
            "url": url,
            "logo_url": None,
            "use_cases": [best_for] if best_for else [],
            "free_alternatives": [],
            "best_prompts": [],
            "pros": [],
            "cons": [],
            "professions": [],
            "start_here_workflow": [],
            "make_money_module": [],
            "irl_use_cases": [],
            "featured": False,
            "trending": False,
            "new_launch": False,
            "updated_recently": False,
            "view_count": 0,
        })
    return out
