"""Expanded seed data with new taxonomy, career packs, and rich tool modules."""

# ---------- CATEGORIES (with parent/subcategory support) ----------
# Top-level groups
GROUPS = [
    {"name": "Personas", "slug": "personas", "description": "Guides curated by profession and skill.", "icon": "Users", "parent_slug": None, "sort": 1},
    {"name": "Business Operations", "slug": "business-ops", "description": "Tools for running & scaling operations.", "icon": "Briefcase", "parent_slug": None, "sort": 2},
    {"name": "Industry Verticals", "slug": "industries", "description": "AI tools for specific industries.", "icon": "Building2", "parent_slug": None, "sort": 3},
    {"name": "Technical & Infrastructure", "slug": "technical", "description": "Data, security, AI infrastructure.", "icon": "Server", "parent_slug": None, "sort": 4},
    {"name": "AI Agents", "slug": "ai-agents", "description": "Autonomous, decision-making AI systems.", "icon": "Bot", "parent_slug": None, "sort": 5},
    {"name": "Automation", "slug": "automation", "description": "Trigger→Action workflows, no judgment.", "icon": "Zap", "parent_slug": None, "sort": 6},
    {"name": "Core Tools", "slug": "core", "description": "Foundational AI tools by modality.", "icon": "Sparkles", "parent_slug": None, "sort": 7},
]

SUBS = [
    # Personas
    ("Students", "students", "personas", "GraduationCap", "Ace assignments, study smarter, learn 2x faster."),
    ("Developers", "developers", "personas", "Code2", "Ship code faster with AI-native editors and agents."),
    ("Researchers", "researchers", "personas", "FlaskConical", "Literature reviews, synthesis, and grant drafting."),
    ("Designers", "designers", "personas", "Palette", "Generate UI, mockups, brand assets in minutes."),
    ("Marketers", "marketers", "personas", "Megaphone", "Content, ads, and social at 10x speed."),
    ("Founders", "founders", "personas", "Rocket", "Research → deck → MVP → launch, solo."),
    ("Freelancers", "freelancers", "personas", "UserRoundCog", "Turn skills into a one-person agency."),
    # Business Ops
    ("Sales & CRM", "sales-crm", "business-ops", "TrendingUp", "AI SDRs, deal intelligence, revenue ops."),
    ("Customer Support", "support", "business-ops", "Headphones", "AI agents resolving tickets 24/7."),
    ("HR & Recruiting", "hr", "business-ops", "Users", "Sourcing, screening, and onboarding at scale."),
    ("Legal & Compliance", "legal", "business-ops", "Scale", "Contract review, drafting, and research."),
    ("Finance & Accounting", "finance", "business-ops", "Landmark", "Bookkeeping, forecasting, and reporting."),
    # Industries
    ("Real Estate & PropTech", "real-estate", "industries", "Home", "Listings, valuations, and tenant automation."),
    ("Ecommerce", "ecommerce", "industries", "ShoppingCart", "Product descriptions, ads, and personalization."),
    ("Healthcare", "healthcare", "industries", "Stethoscope", "Clinical documentation, diagnostics, and triage."),
    ("Education", "education", "industries", "BookOpen", "Tutors, lesson planning, and grading assistants."),
    # Technical
    ("Data & Analytics", "data", "technical", "BarChart3", "Natural-language dashboards and analysis."),
    ("AI Infrastructure", "ai-infra", "technical", "Cpu", "Vector DBs, orchestration, model hosting."),
    ("Security & Privacy", "security", "technical", "ShieldCheck", "AI-powered threat detection and code scanning."),
    # AI Agents
    ("Coding Agents", "coding-agents", "ai-agents", "Terminal", "Devin, Cursor Agent, Claude Code — ship PRs."),
    ("Browser & Computer-Use", "browser-agents", "ai-agents", "MousePointer", "Agents that click, type, and complete web tasks."),
    ("Research Agents", "research-agents", "ai-agents", "Search", "Deep research pipelines with cited answers."),
    ("Sales / SDR Agents", "sdr-agents", "ai-agents", "PhoneCall", "Autonomous prospecting and follow-up."),
    ("Agent Builders (No-code)", "agent-builders", "ai-agents", "Wrench", "Build custom agents without writing code."),
    ("Frameworks (Devs)", "agent-frameworks", "ai-agents", "Braces", "LangGraph, CrewAI, AutoGen — for developers."),
    ("Multi-Agent Orchestration", "multi-agent", "ai-agents", "Network", "Teams of specialized agents working together."),
    # Automation
    ("Workflow Builders", "workflow-builders", "automation", "Workflow", "Zapier, Make, n8n — trigger→action flows."),
    ("Business Process (BPA)", "bpa", "automation", "GitBranch", "End-to-end process automation across teams."),
    ("Document/Data Automation", "doc-automation", "automation", "FileText", "OCR, extraction, and data pipelines."),
    ("Marketing Automation", "marketing-automation", "automation", "Megaphone", "Drip campaigns, lead scoring, retargeting."),
    ("Developer-First Automation", "dev-automation", "automation", "TerminalSquare", "Code-first automation for engineers."),
    ("RPA", "rpa", "automation", "Bot", "Legacy app automation via UI robots."),
    ("E-commerce Sync", "ecom-sync", "automation", "PackageOpen", "Sync orders, inventory, and channels."),
    # Core
    ("Chat & Reasoning", "chat", "core", "MessagesSquare", "General-purpose AI assistants."),
    ("Writing & Content", "writing", "core", "PenLine", "Long-form writing, copywriting, blogging."),
    ("Image Generation", "image", "core", "Image", "Text-to-image, editing, upscaling."),
    ("Video Generation", "video", "core", "Video", "Generate, edit, and avatar videos."),
    ("Audio & Voice", "audio", "core", "AudioLines", "TTS, music generation, voice cloning."),
    ("Code & Developer", "code", "core", "Code2", "Code generation, autocomplete, refactoring."),
    ("Productivity", "productivity", "core", "Sparkles", "Notes, meetings, transcription, focus."),
    ("Research", "research", "core", "FlaskConical", "Search, citations, and knowledge synthesis."),
    ("Design & Presentation", "design", "core", "Palette", "Slides, mockups, and design assistants."),
    ("Marketing & SEO", "marketing", "core", "Megaphone", "SEO, ads, social, and growth."),
]

CATEGORIES = GROUPS + [
    {"name": n, "slug": s, "description": d, "icon": ic, "parent_slug": p, "sort": 10}
    for (n, s, p, ic, d) in SUBS
]


def T(name, slug, tagline, description, category_slugs, pricing, url, use_cases, alts, prompts, pros, cons,
      professions, start_here, make_money, irl, featured=False, trending=False, new_launch=False, updated_recently=False):
    return dict(
        name=name, slug=slug, tagline=tagline, description=description,
        category=category_slugs[0] if category_slugs else "chat",
        category_slugs=category_slugs, pricing=pricing, url=url,
        use_cases=use_cases, free_alternatives=alts, best_prompts=prompts,
        pros=pros, cons=cons, professions=professions,
        start_here_workflow=start_here, make_money_module=make_money, irl_use_cases=irl,
        featured=featured, trending=trending, new_launch=new_launch, updated_recently=updated_recently,
        view_count=0,
    )


TOOLS = [
    T("ChatGPT", "chatgpt", "The original general-purpose AI assistant.",
      "OpenAI's flagship conversational AI for writing, analysis, coding, and brainstorming. Supports images, voice, file uploads, and custom GPTs.",
      ["chat", "students", "marketers"], "freemium", "https://chat.openai.com",
      ["Drafting emails", "Brainstorming", "Code review", "Data analysis"],
      ["Claude (free tier)", "Gemini", "DeepSeek"],
      ["Act as a [role] and help me [task]. Constraints: [...]. Output format: [...]",
       "Summarize this in 5 bullets a beginner can follow: [paste]",
       "Find 3 weak points in this argument and steelman the strongest: [paste]"],
      ["Huge ecosystem", "Custom GPTs", "Best voice mode"],
      ["Limits on free tier", "Sometimes verbose"],
      ["student", "developer", "marketer", "freelancer", "researcher"],
      ["Paste your source material (essay, notes, article) into a new chat.",
       "Give ChatGPT a role + explicit output format ('You are a study coach. Output 10 flashcards as Q/A.').",
       "Iterate: ask it to 'critique its own answer' and produce a v2."],
      [{"title": "AI ghostwriter for LinkedIn founders", "body": "Charge $1.5k–$4k/month to write daily posts using a repeatable ChatGPT + brand-voice prompt."},
       {"title": "Custom GPTs on the GPT Store", "body": "Publish niche GPTs (e.g., YouTube Title Optimizer) and earn revenue share from GPT store."}],
      ["Rewrite a snarky email as diplomatic", "Plan a healthy weekly meal + shopping list", "Summarize a 40-page PDF into a 1-page memo"],
      featured=True, trending=True),

    T("Claude", "claude", "Thoughtful long-form writing & code partner.",
      "Anthropic's Claude is preferred for long documents, careful reasoning, and code tasks. Projects + artifacts make it great for builders.",
      "chat developers researchers".split(), "freemium", "https://claude.ai",
      ["Long-form writing", "Code refactor", "Document Q&A"],
      ["ChatGPT free", "DeepSeek"],
      ["You are an expert editor. Rewrite this for clarity without losing voice: [paste]",
       "Explain this codebase folder structure and the data flow: [paste tree]"],
      ["Best at long context", "Pleasant tone", "Artifacts"],
      ["Stricter on some content", "No image gen"],
      ["developer", "researcher", "freelancer"],
      ["Create a Claude Project and upload your PDFs / source files as knowledge.",
       "Ask Claude to build an Artifact (React component, doc, or chart) directly from the sources.",
       "Iterate the artifact in-place — Claude edits and re-renders live."],
      [{"title": "Grant / RFP writing service", "body": "Use Claude's long-context to draft technical grants in hours. Premium hourly rates."},
       {"title": "Codebase auditor", "body": "Sell '48h codebase review' — Claude produces a full architecture doc + risks."}],
      ["Summarize a 200-page book without losing nuance", "Plan a novel outline with foreshadowing", "Turn meeting notes into a 1-pager"],
      featured=True),

    T("Cursor", "cursor", "The AI-first code editor.",
      "A fork of VS Code with deep AI integration: edit-in-place, agent mode, codebase chat. The default for AI-assisted coding.",
      ["code", "coding-agents", "developers"], "freemium", "https://cursor.com",
      ["Refactor", "New feature scaffolding", "Bug hunt"],
      ["GitHub Copilot free trial", "Continue.dev"],
      ["@codebase how is auth handled? List all files.",
       "Implement the test cases in this file then make them pass."],
      ["Composer is excellent", "Multi-file edits"],
      ["Pro pricing"],
      ["developer"],
      ["Open your repo in Cursor and press ⌘K on any file to describe the change in English.",
       "Use @codebase to ask questions across the whole project.",
       "Switch to Composer (⌘I) for multi-file edits + agent mode."],
      [{"title": "Freelance MVP builder", "body": "Ship MVPs in 2 weeks. Charge $3k-$10k per project."},
       {"title": "Sell boilerplates", "body": "Build niche SaaS starters (auth + payments) and sell on Gumroad."}],
      ["Refactor a legacy file safely", "Generate tests for existing untested code", "Autopilot a small feature in agent mode"],
      featured=True, trending=True),

    T("Perplexity", "perplexity", "AI answer engine with citations.",
      "Search the live web with grounded answers and inline citations.",
      ["research", "research-agents", "students", "researchers"], "freemium", "https://perplexity.ai",
      ["Market research", "Citations", "Fact-check"],
      ["Phind", "You.com"],
      ["Compare latest research on [topic]. Cite peer-reviewed sources.",
       "Current pricing landscape for [category]?"],
      ["Always cited", "Fast", "Free is generous"],
      ["Depth varies"],
      ["student", "researcher", "marketer"],
      ["Pick a focus (Academic / Web / Social) matching your query.",
       "Ask specific questions with constraints (year, region, sources).",
       "Save into a Perplexity Collection to compound research."],
      [{"title": "Research-as-a-service", "body": "Deliver market landscape reports to founders/VCs. $500–$2k per report."},
       {"title": "Paid newsletter", "body": "Curate a subfield newsletter using Perplexity + Substack."}],
      ["Fact-check a viral tweet before sharing", "Compare 3 products with sources", "Get citations for a school essay"],
      trending=True),

    T("Midjourney", "midjourney", "Cinematic, artistic image generation.",
      "The most distinctive aesthetic in AI image generation.",
      ["image", "designers"], "paid", "https://midjourney.com",
      ["Concept art", "Moodboards", "Ad creative"],
      ["Krea", "Ideogram free"],
      ["[subject], [style], shot on Hasselblad, soft natural light --ar 3:2 --style raw"],
      ["Best aesthetic"],
      ["Paid only"],
      ["marketer", "freelancer"],
      ["Craft a prompt with subject → style → camera/lens → mood.",
       "Generate 4 variations, upscale the best, then use vary(region) for edits.",
       "Save your winning prompts as a style ref for consistent branding."],
      [{"title": "Book cover / album art commissions", "body": "Sell covers to indie authors/musicians. $200–$800/each."},
       {"title": "Print-on-demand art", "body": "Upload originals to Redbubble/Society6."}],
      ["Create a wallpaper matching your mood", "Design a birthday card", "Visualize a home renovation idea"],
      featured=True, trending=True),

    T("Suno", "suno", "Generate full songs from a prompt.",
      "Type lyrics or a theme, pick a style, get full songs with vocals and instruments.",
      ["audio"], "freemium", "https://suno.ai",
      ["Jingles", "Demo tracks"],
      ["Udio free tier"],
      ["[genre] song about [topic], female vocals, hopeful chorus"],
      ["Great vocals"],
      ["Commercial licensing depends on plan"],
      ["freelancer", "marketer"],
      ["Write a short lyric or theme description.",
       "Pick style tags (genre + mood + instruments).",
       "Regenerate + Extend to build a full song."],
      [{"title": "Custom jingles for small biz", "body": "$100–$500 per branded jingle."},
       {"title": "Faceless YouTube music channels", "body": "Publish AI-generated lo-fi playlists; monetize via ads."}],
      ["Compose a birthday song for your friend", "Create a workout playlist theme", "Produce a demo for your band"],
      trending=True, new_launch=True),

    T("ElevenLabs", "elevenlabs", "The best AI voice generation.",
      "Hyper-realistic TTS and voice cloning.",
      ["audio", "marketers", "freelancers"], "freemium", "https://elevenlabs.io",
      ["Voiceovers", "Dubbing"],
      ["OpenAI TTS"],
      ["Use voice [Rachel] for a calm, documentary-style narration of: [text]"],
      ["Best quality"],
      ["Paid for high volume"],
      ["freelancer", "marketer"],
      ["Pick a preset voice or clone your own from 60s of audio.",
       "Paste your script; tweak stability & style for tone.",
       "Export MP3 and drop into CapCut / Descript."],
      [{"title": "Audiobook narration service", "body": "Narrate self-published authors' books at scale."},
       {"title": "Voice-over marketplace on Fiverr", "body": "Deliver polished VOs in hours."}],
      ["Voice a bedtime story for your kid", "Narrate your Notion notes for a walk", "Dub your Instagram reel"]),

    T("Runway", "runway", "Pro-grade AI video generation & editing.",
      "Gen-3 lets you produce short cinematic clips.",
      ["video"], "paid", "https://runwayml.com",
      ["Short ads", "B-roll"],
      ["Kling free trial", "Pika"],
      ["Cinematic dolly-in on a foggy forest path, golden hour, anamorphic 2.39:1"],
      ["Cinematic quality"],
      ["Expensive credits"],
      ["marketer", "freelancer"],
      ["Write a shot list with camera moves + lighting.",
       "Generate 5s clips at 720p, iterate on your favorites at 1080p.",
       "Assemble in Runway timeline; add audio via ElevenLabs."],
      [{"title": "Micro-agencies for short-form ads", "body": "TikTok/Instagram ads for DTC brands. $500–$3k per ad."},
       {"title": "Concept trailers", "body": "Sell 30s concept films to indie devs / musicians."}],
      ["Turn a photo into a moving clip", "Make a video birthday card", "Prototype a movie idea"]),

    T("Lovable", "lovable", "Build full-stack apps by chatting.",
      "Describe an app; get React + database + auth. MVPs in a weekend.",
      ["code", "coding-agents", "developers", "founders"], "freemium", "https://lovable.dev",
      ["MVPs", "Prototypes"],
      ["v0 free", "Bolt.new free"],
      ["Build a recipe app with login, save favorites, search by ingredients."],
      ["Fast prototyping"],
      ["Limits on complexity"],
      ["developer", "freelancer"],
      ["Describe the app in one paragraph — include auth, DB, main flows.",
       "Iterate feature-by-feature: 'Now add a leaderboard page.'",
       "Deploy to Vercel or export the code to GitHub."],
      [{"title": "MVP-as-a-service", "body": "Ship pre-launch MVPs in a week to founders. $2k–$5k flat."},
       {"title": "Micro-SaaS launches", "body": "Build your own tiny SaaS in a weekend."}],
      ["Build a fitness tracker in a weekend", "Ship a family recipes app", "Prototype a game jam idea"],
      trending=True, new_launch=True),

    T("v0 by Vercel", "v0", "Generate React + Tailwind UIs from a prompt.",
      "Describe a screen — get production-ready React/Tailwind components.",
      ["code", "designers", "developers"], "freemium", "https://v0.dev",
      ["UI scaffolding", "Landing pages"],
      ["Bolt.new"],
      ["A pricing page with 3 tiers, dark mode, faq section."],
      ["Clean shadcn output"],
      ["Sometimes generic"],
      ["developer", "freelancer"],
      ["Sketch or describe the screen.",
       "Iterate with 'make the hero bolder, add a testimonials strip'.",
       "Copy the code straight into your Next.js repo."],
      [{"title": "Landing pages for founders", "body": "$500–$2k per page + copy."},
       {"title": "Design system starters", "body": "Sell branded shadcn kits on Gumroad."}],
      ["Design a personal site in 10 minutes", "Mock a settings page for feedback"]),

    T("GitHub Copilot", "github-copilot", "Inline AI autocomplete in your IDE.",
      "Autocomplete + chat across VS Code, JetBrains and Neovim.",
      ["code", "developers"], "freemium", "https://github.com/features/copilot",
      ["Autocomplete", "Test gen"],
      ["Codeium free"],
      ["// implement a binary search that returns -1 if not found"],
      ["Mature"],
      ["Less context aware than Cursor"],
      ["developer", "student"],
      ["Install the extension in your IDE.",
       "Write a clear function comment; let Copilot complete.",
       "Use Copilot Chat for edits & explanations."],
      [{"title": "Speed up freelance dev", "body": "Ship features 2× faster; keep hourly rate."}],
      ["Learn a new language faster with inline suggestions"]),

    T("Notion AI", "notion-ai", "AI baked into your notes & docs.",
      "Summarize meetings, generate tables, write briefs — inside Notion.",
      ["productivity", "students"], "freemium", "https://notion.so/product/ai",
      ["Meeting notes", "PRDs"],
      ["Obsidian + plugins"],
      ["Summarize this page into action items grouped by owner."],
      ["Inside your workspace"],
      ["Only as good as Notion"],
      ["student", "marketer", "freelancer"],
      ["Open your Notion doc; press space for AI.",
       "Ask for a table, summary or action items.",
       "Refine with 'shorten', 'change tone', or 'translate'."],
      [{"title": "Notion consultant / template seller", "body": "Sell profession-specific templates on Gumroad."}],
      ["Summarize a class lecture into flashcards", "Turn a brain-dump into a PRD"]),

    T("Otter.ai", "otter", "Meeting transcripts & summaries.",
      "Joins meetings, transcribes, summarizes, extracts action items.",
      ["productivity", "sales-crm"], "freemium", "https://otter.ai",
      ["Meeting notes", "Interviews"],
      ["Tactiq free"],
      ["Summarize this meeting into decisions, action items, risks."],
      ["Solid free tier"],
      ["Accuracy varies"],
      ["student", "marketer", "researcher"],
      ["Connect Otter to Zoom / Google Meet.",
       "Otter auto-joins; live transcribes and highlights.",
       "After the meeting, share the auto-generated summary."],
      [{"title": "Note-taking service for execs", "body": "Sell managed meeting notes to busy founders."}],
      ["Never lose lecture notes", "Recall exactly what your boss said"]),

    T("Descript", "descript", "Edit video by editing text.",
      "Transcribe then edit your podcast/video in a doc.",
      ["video", "freelancers"], "freemium", "https://descript.com",
      ["Podcasts", "YouTube"],
      ["CapCut", "Audacity"],
      ["Remove all filler words and pauses longer than 0.5s."],
      ["Genius for creators"],
      ["Render speed"],
      ["freelancer"],
      ["Upload your recording; Descript transcribes.",
       "Edit the text — the video/audio cuts to match.",
       "Export or send to YouTube / podcast host."],
      [{"title": "Podcast editing agency", "body": "Charge $300–$800 / episode + shorts."}],
      ["Edit your family videos by removing filler"]),

    T("Ideogram", "ideogram", "AI images that actually render text.",
      "Best-in-class for typography, posters, logos.",
      ["image", "designers", "marketers"], "freemium", "https://ideogram.ai",
      ["Posters", "Logos"],
      ["Bing Image Creator"],
      ["A bold poster that says 'GRAND OPENING' with retro 70s typography"],
      ["Text rendering"],
      ["Less artistic than MJ"],
      ["marketer", "freelancer"],
      ["Describe the design + include the exact text in quotes.",
       "Generate 4; upscale or remix.",
       "Download PNG; polish in Canva if needed."],
      [{"title": "Logo/poster gigs", "body": "$50–$300 per design on Fiverr."}],
      ["Design a birthday poster for a friend", "Make a resume header graphic"]),

    T("Gamma", "gamma", "Generate presentations from a prompt.",
      "Type a topic, get a polished deck.",
      ["design", "students", "founders"], "freemium", "https://gamma.app",
      ["Pitch decks"],
      ["Slidesgo + ChatGPT"],
      ["A 10-slide investor deck for a B2B SaaS analytics startup."],
      ["Magic AI"],
      ["Themes can look samey"],
      ["student", "freelancer", "marketer"],
      ["Enter a topic + audience.",
       "Pick a theme; Gamma builds the deck.",
       "Refine each card with the sidebar AI."],
      [{"title": "Pitch deck writer for founders", "body": "$500–$2k per deck."}],
      ["Make a wedding recap slideshow", "Present your class project"]),

    T("DeepSeek", "deepseek", "Free, strong reasoning model.",
      "Open and free chat model.",
      ["chat", "students"], "free", "https://chat.deepseek.com",
      ["Code", "Math"],
      [],
      ["Solve this LeetCode problem step by step."],
      ["Free"],
      ["Privacy considerations"],
      ["student", "developer"],
      ["Ask your question; toggle DeepThink for math/code.",
       "Iterate: 'try a different approach'.",
       "Copy the reasoning into your notes."],
      [{"title": "Tutor with a free stack", "body": "Undercut competitors while using DeepSeek + Perplexity."}],
      ["Free ChatGPT alternative for daily use"]),

    T("Zapier", "zapier", "Connect 6000+ apps with no-code triggers.",
      "The godfather of no-code automation.",
      ["workflow-builders", "marketers", "founders"], "freemium", "https://zapier.com",
      ["Lead capture → CRM", "Slack alerts", "Report scheduling"],
      ["Make.com"],
      ["When [trigger] happens, do [action] and update [tool]."],
      ["Huge app catalog"],
      ["Task-based pricing"],
      ["marketer", "freelancer"],
      ["Pick a trigger app (e.g., Typeform new submission).",
       "Pick an action app + fields to send.",
       "Test with a real submission; enable the Zap."],
      [{"title": "Automation consultant", "body": "Charge $80–$200/hr to build Zaps for SMBs."}],
      ["Auto-save email attachments to Drive"]),

    T("Make.com", "make", "Visual automation with logic + branching.",
      "Powerful visual scenarios with routers, filters, error handling.",
      ["workflow-builders", "developers", "marketers"], "freemium", "https://make.com",
      ["Complex scenarios", "Bulk operations"],
      ["Zapier free tier"],
      ["Route [data] with condition [x]; if true → [A], else → [B]"],
      ["Cheaper than Zapier at scale"],
      ["Steeper curve"],
      ["marketer", "developer"],
      ["Design your scenario visually — modules linked as a flow.",
       "Add filters and routers for branching logic.",
       "Schedule or trigger via webhook."],
      [{"title": "Ops-in-a-box for agencies", "body": "Sell full automation setups to marketing agencies."}],
      ["Automate personal finance reports"]),

    T("n8n", "n8n", "Open-source, self-hostable automation.",
      "Devs love it: nodes, code, self-hosting.",
      ["workflow-builders", "dev-automation", "developers"], "freemium", "https://n8n.io",
      ["Self-hosted automations"],
      [],
      ["Custom nodes with JS/Python inline."],
      ["Self-hostable", "Free"],
      ["Setup effort"],
      ["developer"],
      ["Self-host on a $5 VPS or use n8n cloud.",
       "Drag nodes to build your workflow.",
       "Add a Code node for anything custom."],
      [{"title": "Sell managed self-hosted automations", "body": "Offer monthly retainers for hosted flows."}],
      ["Personal news digest to Telegram"],
      new_launch=True),

    T("Devin", "devin", "Autonomous software engineer.",
      "An agent that codes end-to-end tickets on its own machine.",
      ["coding-agents", "ai-agents"], "paid", "https://devin.ai",
      ["Bug triage", "Feature stubs"],
      ["OpenDevin"],
      ["Fix ticket #123: 'checkout button broken on Safari'."],
      ["Truly autonomous"],
      ["Expensive"],
      ["developer"],
      ["Give Devin a Linear/Jira ticket.",
       "Watch it plan, code, and open a PR.",
       "Review + merge or ask for changes."],
      [{"title": "Managed backlog service", "body": "Small-team retainer to burn down backlogs autonomously."}],
      ["Automate boring code chores"],
      new_launch=True, trending=True),

    T("Manus", "manus", "General-purpose autonomous browser agent.",
      "Takes long-horizon tasks in the browser: research, purchase, publish.",
      ["browser-agents", "ai-agents"], "freemium", "https://manus.im",
      ["Long research", "Web tasks"],
      ["Browserbase"],
      ["Book me the cheapest flight from BLR to LHR next Friday."],
      ["Long-horizon"],
      ["Occasional errors"],
      ["freelancer", "founder"],
      ["Describe the goal + constraints (budget, deadline).",
       "Let it plan; approve major decisions.",
       "It executes across tabs & sites."],
      [{"title": "AI VA-as-a-service", "body": "Sell 'AI assistant hours' to solopreneurs."}],
      ["Book travel end-to-end"],
      new_launch=True),

    T("HubSpot AI", "hubspot-ai", "AI baked into a CRM.",
      "Content Assistant, ChatSpot, and Breeze features.",
      ["sales-crm", "business-ops"], "freemium", "https://hubspot.com",
      ["Sales sequences", "Content"],
      ["Attio + ChatGPT"],
      ["Draft a follow-up email from this call transcript."],
      ["CRM-native"],
      ["Priciest tiers"],
      ["marketer"],
      ["Connect your inbox + calendar.",
       "Use ChatSpot to ask 'top 5 deals stuck this month'.",
       "Auto-draft replies + log interactions."],
      [{"title": "HubSpot implementation partner", "body": "Certified partners earn $150–$300/hr."}],
      ["Track personal side-hustle leads"]),

    T("Intercom Fin", "fin", "AI customer-support agent.",
      "Resolves customer questions from your help center.",
      ["support", "business-ops"], "paid", "https://intercom.com/fin",
      ["Tier 1 support"],
      ["Chatbase"],
      ["Answer using this help center; escalate to human if unsure."],
      ["Enterprise ready"],
      ["Per-resolution pricing"],
      ["marketer"],
      ["Point Fin to your help center + docs.",
       "Set escalation rules.",
       "Monitor resolution rate + train on gaps."],
      [{"title": "CX automation consultant", "body": "Deploy Fin for SMBs; charge setup + monthly."}],
      ["Auto-answer FAQs on your personal site"]),

    T("Fathom (Analytics for Agents)", "fathom-agents", "AI meeting notetaker + CRM sync.",
      "Free AI notetaker with CRM integrations.",
      ["sdr-agents", "productivity", "sales-crm"], "free", "https://fathom.video",
      ["Sales calls"],
      ["Otter"],
      ["Generate a follow-up email summarizing this call + next steps."],
      ["Free, great UX"],
      [],
      ["marketer", "freelancer"],
      ["Install; approve joining your Zoom/Meet.",
       "After each call get an AI summary + follow-up email.",
       "Sync into HubSpot/Salesforce."],
      [{"title": "SDR outsourcing", "body": "Sell 'follow-ups within 5 minutes' as an SLA."}],
      ["Recall exactly what a client said"]),

    T("Canva Magic Studio", "canva-magic-studio", "AI inside the most-loved design tool.",
      "Magic Design, Magic Write, background remove, brand kit.",
      ["design", "marketers", "freelancers"], "freemium", "https://canva.com",
      ["Social posts", "Pitch decks"],
      ["Photopea + free tools"],
      ["Magic Design: a launch announcement for a SaaS, modern, mint and black."],
      ["Massive template library"],
      ["Pro paywall"],
      ["marketer", "freelancer", "student"],
      ["Start from a Magic Design prompt or an existing template.",
       "Use Magic Write / brand voice for the copy.",
       "Export to social platforms directly."],
      [{"title": "Social media manager", "body": "Manage 3-4 SMBs at $500–$1.5k/mo each."}],
      ["Design a personal newsletter header"]),

    T("HeyGen", "heygen", "Avatar videos & dubbing in 40+ languages.",
      "Best-in-class dubbing for short-form video.",
      ["video", "marketers"], "freemium", "https://heygen.com",
      ["Dub TikToks", "Spokesperson"],
      ["CapCut + ElevenLabs"],
      ["Dub this English video to Spanish, match lip movement."],
      ["Multilingual"],
      ["Watermarks on free"],
      ["marketer", "freelancer"],
      ["Upload a talking-head video.",
       "Pick target languages; HeyGen dubs + syncs lips.",
       "Export vertical for Reels/TikTok."],
      [{"title": "AI-localized ads service", "body": "Charge per additional language."}],
      ["Dub a travel vlog for friends in another language"]),
]

# ---------- CAREER PACKS (imported from seed_packs.py — 50 packs) ----------
from seed_packs import CAREER_PACKS_50 as CAREER_PACKS


# ---------- FAQ ----------
FAQ = [
    {"q": "Which one should I use?", "a": "Use the AI Chat (bottom right) — describe your task, get a shortlist. Or explore Career Packs for pre-built stacks."},
    {"q": "How do I use it?", "a": "Every tool page has a 'Start Here' 3-step workflow written specifically for the tool's #1 use case."},
    {"q": "What prompt works?", "a": "Check the 'Best Prompts' section on each tool page — battle-tested prompts you can copy-paste."},
    {"q": "Can I replace ChatGPT with something free?", "a": "Yes. See Free Alternatives on the ChatGPT page (Claude free tier, Gemini, DeepSeek)."},
    {"q": "Can this help me earn money?", "a": "Every tool page and every Career Pack has a 'Make Money With This' module with concrete strategies + typical earnings."},
    {"q": "Which combination of tools should I learn?", "a": "Career Packs group 5–6 tools that chain together. Start with the pack matching your role."},
]

# ---------- ROADMAP ----------
ROADMAP = [
    {"phase": "Now (Q1 2026)", "status": "shipped", "items": ["500+ curated tools", "By-profession guides", "AI recommender chat", "Career packs"]},
    {"phase": "Next (Q2 2026)", "status": "in-progress", "items": ["User bookmarks & lists", "Weekly tool digest email", "Community-submitted prompts", "Comparisons page"]},
    {"phase": "Later (Q3 2026)", "status": "planned", "items": ["Live agent playground", "Verified reviews", "Course + certification track", "Affiliate revenue split for creators"]},
]
